### ISSUE TITLE
New logo/icon Proposal

### ISSUE THREAD

**Issue by mansya** [samayo/Autolog#3]
Can I contribute about the new logo with your project?

**Comment by samayo** [comment]
Hey, if it is similar to the last one, then I don't want to waste your time. I will give you more info when I find similar logo and then you can start if you want.

**Comment by mansya** [comment]
I will try to design for this one. because it has a free time for now. and also fun for me :-D

**Comment by samayo** [comment]
No. Just wait until I get the time to share it with you. It is hard to satisfy me with design, specially since I am a big fan graphic design so, don't waste your time. I will make a quick sketch and let you know what to do, if you want to do it. If you spend now hours and I don't like it, then your time will have been a waste for nothing and I will feel bad about it.

**Comment by mansya** [comment]
ok. I will wait.
